import { betterAuth } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";

import { db } from "@/database/client";
import { schema } from "@/database/schema";

export const auth = betterAuth({
  database: drizzleAdapter(db, {
    provider: "sqlite",
    schema: schema,
    usePlural: true,
  }),
  logger: console,
  emailAndPassword: {
    enabled: true,
  },
  advanced: {
    // Generated by database.
    generateId: false,
  },
});
