name = "<APP_NAME>"
main = "./dist/_worker.js/index.js"
compatibility_date = "2024-10-06"
compatibility_flags = [
  "nodejs_compat_v2",
  "nodejs_als",       # nodsjs_als is AsyncLocalStorage
]
send_metrics = false
minify = false

[vars]
ENVIRONMENT = "dev"

[observability]
# See https://developers.cloudflare.com/workers/wrangler/configuration/#observability
enabled = false
head_sampling_rate = 0.1 # 10% of requests are logged
