name = "solid-quickstart"
main = "./dist/_worker.js/index.js"
compatibility_date = "2024-10-06"
compatibility_flags = [
  "nodejs_compat_v2",
  "nodejs_als",       # nodsjs_als is AsyncLocalStorage
]
send_metrics = false
minify = false

[vars]
ENVIRONMENT = "dev"
API_URL = "https://localhost:8787"
