import type { Session, User } from "@/db/schemas/auth";
// Generated by Wrangler by running `wrangler types ./src/env.d.ts`
import type {
  Request as CfRequest,
  ExecutionContext,
} from "@cloudflare/workers-types";

interface Env {
  ENVIRONMENT: "dev" | "prod";
  API_URL: "https://localhost:8787";
}

declare module "vinxi/http" {
  interface H3EventContext {
    cf: CfRequest["cf"];
    cloudflare: {
      request: Request;
      env: Env;
      context: ExecutionContext;
    };
  }
}

declare module "hono" {
  interface Bindings extends Env {}
  interface Variables {
    user: User | null;
    session: Session | null;
  }
}
